ERRCOMM.LS     Robot Name ROBOT 23-FEB-26 19:14:40  

1" 23-FEB-26 18:18:54 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
2" 23-FEB-26 16:33:38 " HOST-209 SM: Connection Aborted                   " " WARN                          00000000" 
3" 23-FEB-26 14:29:56 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
4" 23-FEB-26 12:27:02 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
5" 23-FEB-26 12:16:44 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
6" 20-FEB-26 15:55:30 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
