ERRMOT.LS      Robot Name ROBOT 20-FEB-26 19:15:40  

1" 20-FEB-26 18:58:06 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
2" 20-FEB-26 18:54:58 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
3" 20-FEB-26 18:24:00 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
4" 20-FEB-26 15:55:32 " SRVO-307 HBK close/HBK enabled (G:1)              " " WARN                          00000000" 
